// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwH4dDAfqZznP11hjspsLtTrbB0hAE5GY',
    appId: '1:733443225670:web:62d93103d3e1342b92b247',
    messagingSenderId: '733443225670',
    projectId: 'vitta-5ec1e',
    authDomain: 'vitta-5ec1e.firebaseapp.com',
    storageBucket: 'vitta-5ec1e.firebasestorage.app',
    measurementId: 'G-B2H54PWY31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsfC6Rpdwmear_5zxDJCUWNTiV_sl56uQ',
    appId: '1:733443225670:android:905a0fac647df2cd92b247',
    messagingSenderId: '733443225670',
    projectId: 'vitta-5ec1e',
    storageBucket: 'vitta-5ec1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyvFUiOFLSuwqISQ-D-dri89SBXx1cqz8',
    appId: '1:733443225670:ios:8823964cc7e8a72692b247',
    messagingSenderId: '733443225670',
    projectId: 'vitta-5ec1e',
    storageBucket: 'vitta-5ec1e.firebasestorage.app',
    iosBundleId: 'com.example.vittaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyvFUiOFLSuwqISQ-D-dri89SBXx1cqz8',
    appId: '1:733443225670:ios:8823964cc7e8a72692b247',
    messagingSenderId: '733443225670',
    projectId: 'vitta-5ec1e',
    storageBucket: 'vitta-5ec1e.firebasestorage.app',
    iosBundleId: 'com.example.vittaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwH4dDAfqZznP11hjspsLtTrbB0hAE5GY',
    appId: '1:733443225670:web:a173f2b264a4d39292b247',
    messagingSenderId: '733443225670',
    projectId: 'vitta-5ec1e',
    authDomain: 'vitta-5ec1e.firebaseapp.com',
    storageBucket: 'vitta-5ec1e.firebasestorage.app',
    measurementId: 'G-DCRFSGP0NF',
  );
}
